### PR TITLE
Title should only return the first element

### PR DESCRIPTION
**Pull request by shwanton**

### CODE REVIEW

**Comment by Kikobeats** [comment]
Nice!

Can you use [.getValue method from metascraper.helper](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L48)? it returns the first value with result.

**Comment by shwanton** [comment]
Oops, meant to open this PR on the fork.

**Comment by shwanton** [comment]
I'll open a different one that addresses this.

**Comment by Kikobeats** [comment]
👍

**Pull request closed without merging**
