### PR TITLE
Incorrect URL Return Value

### PR DESCRIPTION
**Pull request by nhahn**
Two issues: 

1. The url wasn't being properly passed into the rule through the wrapper. So in the last case, when none of the html tags are present, this method was returning a null value when it should have defaulted to the original URL

2. Many `canonical` tags now have relative URLs. This wasn't dealt with before, however there is now logic to resolve those URLs against the main url and return that value.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @nhahn looks good! Would you be interested if I added you as a collaborator on GitHub and NPM so you can merge these kinds of things in the future?

**Comment by nhahn** [comment]
Sure thing! I'm actively using this in one of my projects, so if I notice anything else I'll go ahead and fix it. I'm **nphahn** on npm

**Comment by ianstormtaylor** [comment]
Awesome, just added you!

Feel free to merge this one and release it as your first 😄  (there's an `npm run release` script).

**Comment by mahnuh** [comment]
Hey @nhahn would you mind resolving the conflict? Then we can release both our pull requests to npm.

**Pull request closed without merging**
