### PR TITLE
docs: remove 404 packages homepage

### PR DESCRIPTION
**Pull request by makepanic**

### CODE REVIEW

**Comment by makepanic** [comment]
I'm not sure if that's the correct solution as some packages documentup links still work.

**Comment by Kikobeats** [comment]
oh, thanks a lot!

Can you change https://github.com/microlinkhq/metascraper/blob/295bc22476195ad20468850193cf369236f15e6a/packages/metascraper-clearbit-logo/package.json as well? 🙂

**Comment by makepanic** [comment]
Should all documentup.com links be changed? I left clearbit-logo in as it's returning a valid documentation page.

**Comment by Kikobeats** [comment]
Oh, then just the route path of the file is wrong.

Just update it with the correct route should work, eg:
https://nicedoc.io/microlinkhq/metascraper/packages/metascraper-amazon

(nicedoc is my own replacement for documentup 🙂)

**Comment by Kikobeats** [comment]
closed in favour of https://github.com/microlinkhq/metascraper/pull/160, thanks for all 🙂

**Pull request closed without merging**
