### PR TITLE
Add AMP url package

### PR DESCRIPTION
**Pull request by EricPKerr**
This adds support to extract a publisher's Google AMP html tag from the header.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Hello @EricPKerr, thank for this PR.

Instead of creating a new package domain I feel we need to add `amphtml` rule inside [metascraper-url](https://github.com/microlinkhq/metascraper/blob/db5486fb97d87c852d73c5872d226b4511ba9a3e/packages/metascraper-url/index.js#L25) package

Related: https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery/

thoughts?

**Comment by EricPKerr** [comment]
@Kikobeats I think you would want to know specifically if an AMP format is available (we want to link to it in a mobile app), but not always have that be prioritized over the other ones if it was in the `metascraper-url` package.

**Comment by Kikobeats** [comment]
understood!

My concern is, the rest of the packages we are officially maintaining are normalizing different markup vendors over the HTML (open graph, twitter, itemprop, json+ld).

In that case, the only rule we have here is `amphtml`, so actually we are not adding so much value than just extract the value using cheerio.

For that reason, I don't feel too comfortable adding this into core repository. Instead, what do you think if you ship this package under your personal account and we link it into the readme?

**Comment by Kikobeats** [comment]
Closing since I prefer to wait until see a clear future for AMP things

**Comment by EricPKerr** [comment]
Well that's disappointing.

AMP has been a format that publishers have been using for 4+ years.

**Pull request closed without merging**
