### PR TITLE
chore(metascrapper-date): addd time.published

### PR DESCRIPTION
**Pull request by slavaGanzin**

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks for the PR!

Can you tell me an URL that uses `time.published` as meta tag? I want to add a new integration test for that 🙂

**Comment by slavaGanzin** [comment]
> Can you tell me an URL that uses time.published as meta tag? I want to add a new integration test for that slightly_smiling_face

I'll tell you if I will find it again

**Comment by Kikobeats** [comment]
Can you reference any content on the Internet using `time.published` meta tag? I'm not finding anything about it

**Comment by Kikobeats** [comment]
Closing until the original author replies with more information about that

**Pull request closed without merging**
