### PR TITLE
build:(metascraper-audio): detect source from audio URLs

### PR DESCRIPTION
**Pull request by goleary**
I added the audio rule that we talked about in #338  + a unit test. Some formatting in [the test](https://github.com/microlinkhq/metascraper/pull/339/files#diff-ae959c5639fc734762b0a8c78ac8f00f69124960c52ba3634d630c18fcab541b) was changed during the commit hook (I didn't change any formatting on my own).

This will look for links (`<a>` tags) with an `href` that contains an audio file extension (as already defined by the package).

I'm not sure how to generate the test snapshot (didn't see anything in the [contrib doc](https://github.com/microlinkhq/metascraper/blob/master/CONTRIBUTING.md) about using a snapshot vs `should...`), so I may need your help/guidance on doing that @Kikobeats.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Hey thanks for this, let me add some integrations tests there.

You mentioned some URLs that take the benefit of this. Do you remember those URLs?

**Comment by goleary** [comment]
Awesome!

Here are 3:
```
  "https://www.npr.org/2020/12/23/949764249/fork-the-government",
  "https://www.wnycstudios.org/podcasts/radiolab/articles/wubi-effect",
  "https://reactpodcast.com/episodes/117"
```
It seems like there may be an issue with the last one which I haven't had a chance to look in to yet.

**Comment by goleary** [comment]
Actually, I think the last one (https://reactpodcast.com/episodes/117) doesn't work because I was using `got` to fetch the page and it's an SPA.

So it should work when run through [browserless](https://github.com/microlinkhq/browserless).

**Comment by Kikobeats** [comment]
landed at `v5.16.8` 🎉

**Comment by Kikobeats** [comment]
@goleary do you think could be worth it to add a similar rule but for video?

https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-video/index.js

**Comment by goleary** [comment]
Maybe...

We aren't focusing on video the same way we are on audio right now so I really hadn't thought about.  TBH I haven't come across any instances of download links for videos. 

Podcasts are more openly distributed than video (youtube, vimeo, etc.) and this technique obviously wouldn't help there.

If I come across any instances of download links for video I'll circle back, but until I have some real life examples I don't see it being _super_ useful.


Thanks for your help with the tests!

Any idea when I should expect [microlink](https://api.microlink.io/?url=https://www.npr.org/2020/12/23/949764249/fork-the-government&audio) to start using this codepath?

**Comment by Kikobeats** [comment]
@goleary it's already deployed:

https://api.microlink.io/?url=https://www.npr.org/2020/12/23/949764249/fork-the-government&audio

🙂

**Comment by goleary** [comment]
unreal, it's working for me.  Thanks @Kikobeats !!

**Pull request merged**
