### PR TITLE
Fix metascraper-date's incorrect parsing of dates

### PR DESCRIPTION
**Pull request by theQuazz**
Here is an example page which currently has an incorrectly parsed date:

https://www.health.govt.nz/about-ministry/legislation-and-regulation/regulatory-impact-statements/quality-improvement-agency-health-quality-and-safety-commission-functions-powers-and-funding

The HTML which is extracted to find the date string is

```html
<p class="page_updated">Page last updated: <span class="date">07 April 2011</span></p>
```

Currently the extracted date is `201107-04-07` because the selector matches multiple elements (`p.page_updated`, `span.date`) which overlap resulting in the extracted text being:

```
"Page last updated: 07 April 201107 April 2011"
```

This pull request fixes this bug by mapping over each matched element and attempting to parse it as a date, returning the first successful match from that selector. With the fix, the date on this page is
correctly parsed as `2017-04-07`.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks for the PR!

I have a helper called [`$filter`](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L103) for that purpose, It returns the first truthy element from a collection. 

Can you use it instead? For illustrating, you can see [how it is used around the code](https://github.com/microlinkhq/metascraper/search?q=%24filter&unscoped_q=%24filter). Also, you can use it before `wrap` method.

**Comment by theQuazz** [comment]
@Kikobeats you're welcome! I've updated the pull request to use `$filter`, let me know if you would like me to update it further.

**Comment by Kikobeats** [comment]
I added your url as test and also updated snapshots; it fixed some wrong date, so this PR is gold! 🙏

**Comment by theQuazz** [comment]
Great, thank you for your help on this PR! Quick question on https://github.com/microlinkhq/metascraper/pull/164/commits/aa714664320014ea99c62c454f7949bb891ffa6c, wouldn't that prevent us from finding a date in the case that the first element matched has text but doesn't contain an actual date? Here is my highly contrived example:

```javascript
// matched elements in html:
[
    "<div class="date">The publishing date is:</div>",
    "<div class="publishing-date">April 4, 2019</div>"
]
```

**Comment by Kikobeats** [comment]
I removed that code because it's redundant since $filter default function is basically the [same](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L101).

Also, `wrap` method is being sure the value passed can be cast into a valid date, so at the end, it's doing the same thing 🙂

**Pull request merged**
